@BASE_URL=http://localhost:8081

GET {{BASE_URL}}/users

###
GET {{BASE_URL}}/users/333


###
POST  {{BASE_URL}}/users
Content-Type: application/json

{
    "id": 8,
    "nama" : "Ucup2"
}

###
PATCH  {{BASE_URL}}/users/8
Content-Type: application/json

{
    "nama": "Rembulan Malam"
}

###
DELETE  {{BASE_URL}}/users/8